version: 2

before:
  hooks:
    - sh -c 'mkdir -p _out && rm -rf _out/chart && cp -r deploy/infomaniak-webhook _out/chart'
    - 'sed -i "s/^version:.*/version: {{ .Version }}/" _out/chart/Chart.yaml'
    - 'sed -i "s/^appVersion:.*/appVersion: {{ .Version }}/" _out/chart/Chart.yaml'
    - sh -c 'helm package _out/chart --destination _out'
    - make rendered-manifest.yaml CHART=_out/chart

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: cert-manager-webhook-infomaniak
    ldflags:
      - -s -w -extldflags "-static"

archives:
  - formats: [binary]

checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    signature: "${artifact}.sig"

dockers:
  - image_templates:
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-amd64
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=cert-manager webhook for Infomaniak DNS"
      - "--label=org.opencontainers.image.source=https://github.com/Infomaniak/cert-manager-webhook-infomaniak"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - image_templates:
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-arm64
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=cert-manager webhook for Infomaniak DNS"
      - "--label=org.opencontainers.image.source=https://github.com/Infomaniak/cert-manager-webhook-infomaniak"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}
    image_templates:
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-amd64
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-arm64
  - name_template: ghcr.io/infomaniak/cert-manager-webhook-infomaniak:latest
    image_templates:
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-amd64
      - ghcr.io/infomaniak/cert-manager-webhook-infomaniak:{{ .Version }}-arm64

release:
  extra_files:
    - glob: _out/rendered-manifest.yaml
      name_template: rendered-manifest.yaml
